import { Activity, ArrowUpRight, Clock3, Radio, ShieldCheck } from "lucide-react";
import { auditEvents } from "@/lib/demo-data";

export default function Page() {
  return <section className="command-centre"><header className="command-header"><div className="command-title-group"><div className="command-kicker"><Radio size={14} /> Governance trail</div><h1>Audit Events</h1><p>Transparent examples of material platform activity and accountability.</p></div><span className="demo-status"><i /> Immutable preview</span></header>
    <div className="command-metrics"><article className="command-metric tone-cyan"><div className="metric-top"><span>Recorded events</span><Activity size={18} /></div><strong>{auditEvents.length}</strong><div className="metric-foot"><span>Demo activity trail</span><ArrowUpRight size={14} /></div></article><article className="command-metric tone-cyan"><div className="metric-top"><span>Named actors</span><ShieldCheck size={18} /></div><strong>{new Set(auditEvents.map((event) => event.actor)).size}</strong><div className="metric-foot"><span>Accountable users</span></div></article><article className="command-metric tone-cyan"><div className="metric-top"><span>Entity types</span><Activity size={18} /></div><strong>{new Set(auditEvents.map((event) => event.entity)).size}</strong><div className="metric-foot"><span>Controlled records</span></div></article><article className="command-metric tone-amber"><div className="metric-top"><span>Retention</span><Clock3 size={18} /></div><strong>Full</strong><div className="metric-foot"><span>Enterprise mode design</span></div></article></div>
    <article className="command-panel"><div className="panel-heading"><div><span className="panel-label">Activity register</span><h2>Material change history</h2></div><span className="panel-meta">Most recent first</span></div><div className="project-register" role="table" aria-label="Audit events"><div className="project-row project-row-head" role="row"><span>Event</span><span>Entity</span><span>Actor</span><span>Timestamp</span></div>{auditEvents.map((event) => <div className="project-row" role="row" key={event.id}><div><strong>{event.action.replaceAll("_", " ")}</strong><small>Recorded platform event</small></div><div><span>{event.entity}</span><small>Controlled record</small></div><div><strong>{event.actor}</strong><small>authenticated identity</small></div><div><strong>{event.time}</strong><small>audit timestamp</small></div></div>)}</div></article>
  </section>;
}
