import { ArrowUpRight, CheckCircle2, ClipboardCheck, Radio } from "lucide-react";
import { qaReviews } from "@/lib/demo-data";

export default function Page() {
  const approved = qaReviews.filter((review) => review.status === "APPROVED").length;
  const changes = qaReviews.filter((review) => review.status === "CHANGES_REQUIRED").length;
  return <section className="command-centre"><header className="command-header"><div className="command-title-group"><div className="command-kicker"><Radio size={14} /> Technical governance</div><h1>QA Reviews</h1><p>Independent review status and actions required before controlled issue.</p></div><span className="demo-status"><i /> Assurance register</span></header>
    <div className="command-metrics"><article className="command-metric tone-cyan"><div className="metric-top"><span>QA reviews</span><ClipboardCheck size={18} /></div><strong>{qaReviews.length}</strong><div className="metric-foot"><span>Controlled outputs</span><ArrowUpRight size={14} /></div></article><article className="command-metric tone-cyan"><div className="metric-top"><span>Approved</span><CheckCircle2 size={18} /></div><strong>{approved}</strong><div className="metric-foot"><span>Ready for issue</span></div></article><article className="command-metric tone-magenta"><div className="metric-top"><span>Changes required</span><ClipboardCheck size={18} /></div><strong>{changes}</strong><div className="metric-foot"><span>Action before approval</span></div></article><article className="command-metric tone-amber"><div className="metric-top"><span>In review</span><ClipboardCheck size={18} /></div><strong>{qaReviews.filter((q) => q.status === "IN_REVIEW").length}</strong><div className="metric-foot"><span>Reviewer active</span></div></article></div>
    <article className="command-panel"><div className="panel-heading"><div><span className="panel-label">Assurance register</span><h2>Technical reviews</h2></div><span className="panel-meta">{qaReviews.length} records</span></div><div className="project-register" role="table" aria-label="QA reviews"><div className="project-row project-row-head" role="row"><span>Deliverable</span><span>Project / reviewer</span><span>Review state</span><span>Required action</span></div>{qaReviews.map((review) => <div className="project-row" role="row" key={review.id}><div><strong>{review.deliverable}</strong><small>Technical deliverable</small></div><div><span>{review.project}</span><small>Reviewer: {review.reviewer}</small></div><div><span className={`rag-chip ${review.status === "APPROVED" ? "rag-green" : review.status === "CHANGES_REQUIRED" ? "rag-red" : "rag-amber"}`}><i />{review.status.replaceAll("_", " ")}</span></div><div><strong className={review.status === "CHANGES_REQUIRED" ? "text-risk" : "text-positive"}>{review.action}</strong><small>QA control note</small></div></div>)}</div></article>
  </section>;
}
