import { ArrowUpRight, Radio, Users } from "lucide-react";
import { resources } from "@/lib/demo-data";

export default function Page() {
  const over = resources.filter((resource) => resource.planned > resource.capacity).length;
  const utilisation = Math.round(resources.reduce((sum, item) => sum + item.planned, 0) / resources.reduce((sum, item) => sum + item.capacity, 0) * 100);
  return <section className="command-centre"><header className="command-header"><div className="command-title-group"><div className="command-kicker"><Radio size={14} /> Capacity control</div><h1>Resources</h1><p>Weekly allocation, discipline coverage and workload pressure.</p></div><span className="demo-status"><i /> Week of 22 June</span></header>
    <div className="command-metrics"><article className="command-metric tone-cyan"><div className="metric-top"><span>Team members</span><Users size={18} /></div><strong>{resources.length}</strong><div className="metric-foot"><span>Allocated this week</span><ArrowUpRight size={14} /></div></article><article className="command-metric tone-cyan"><div className="metric-top"><span>Utilisation</span><Users size={18} /></div><strong>{utilisation}%</strong><div className="metric-foot"><span>Planned against capacity</span></div></article><article className="command-metric tone-magenta"><div className="metric-top"><span>Overallocated</span><Users size={18} /></div><strong>{over}</strong><div className="metric-foot"><span>Workload intervention</span></div></article><article className="command-metric tone-amber"><div className="metric-top"><span>Disciplines</span><Users size={18} /></div><strong>{new Set(resources.map((r) => r.discipline)).size}</strong><div className="metric-foot"><span>Active capability areas</span></div></article></div>
    <article className="command-panel"><div className="panel-heading"><div><span className="panel-label">People control</span><h2>Weekly capacity plan</h2></div><span className="panel-meta">Hours planned / available</span></div><div className="resource-bars">{resources.map((resource) => { const load = Math.round(resource.planned / resource.capacity * 100); return <div key={resource.id}><span><strong>{resource.person}</strong><em className={load > 100 ? "text-risk" : "text-positive"}>{resource.planned}h / {resource.capacity}h · {load}%</em></span><div><i className={load > 100 ? "over" : "normal"} style={{ width: `${Math.min(load, 100)}%` }} /></div><small>{resource.discipline} · {resource.project} · week of {resource.week}</small></div>; })}</div></article>
  </section>;
}
