import { ArrowUpRight, CheckSquare, Clock3, Radio } from "lucide-react";
import { actions } from "@/lib/demo-data";

export default function Page() {
  const overdue = actions.filter((action) => action.status === "OVERDUE").length;
  const active = actions.filter((action) => action.status === "IN_PROGRESS").length;
  return <section className="command-centre"><header className="command-header"><div className="command-title-group"><div className="command-kicker"><Radio size={14} /> Action control</div><h1>Actions</h1><p>Owned interventions, priorities, due dates and escalation state.</p></div><span className="demo-status"><i /> Demo register</span></header>
    <div className="command-metrics"><article className="command-metric tone-cyan"><div className="metric-top"><span>Tracked actions</span><CheckSquare size={18} /></div><strong>{actions.length}</strong><div className="metric-foot"><span>Portfolio total</span><ArrowUpRight size={14} /></div></article><article className="command-metric tone-magenta"><div className="metric-top"><span>Overdue</span><Clock3 size={18} /></div><strong>{overdue}</strong><div className="metric-foot"><span>Escalation required</span></div></article><article className="command-metric tone-amber"><div className="metric-top"><span>In progress</span><Clock3 size={18} /></div><strong>{active}</strong><div className="metric-foot"><span>Owner response active</span></div></article><article className="command-metric tone-magenta"><div className="metric-top"><span>Critical priority</span><CheckSquare size={18} /></div><strong>{actions.filter((a) => a.priority === "CRITICAL").length}</strong><div className="metric-foot"><span>Director visibility</span></div></article></div>
    <article className="command-panel"><div className="panel-heading"><div><span className="panel-label">Delivery control</span><h2>Action register</h2></div><span className="panel-meta">{actions.length} records</span></div><div className="project-register" role="table" aria-label="Actions"><div className="project-row project-row-head" role="row"><span>Action</span><span>Project / owner</span><span>Priority</span><span>Due status</span></div>{actions.map((action) => <div className="project-row" role="row" key={action.id}><div><strong>{action.description}</strong><small>Controlled project action</small></div><div><span>{action.project}</span><small>{action.owner}</small></div><div><span className={`rag-chip ${action.priority === "CRITICAL" ? "rag-red" : action.priority === "HIGH" ? "rag-amber" : "rag-green"}`}><i />{action.priority}</span></div><div><strong className={action.status === "OVERDUE" ? "text-risk" : "text-positive"}>{action.status.replace("_", " ")}</strong><small>Due {action.due}</small></div></div>)}</div></article>
  </section>;
}
