import { AlertTriangle, ArrowUpRight, Radio, ShieldAlert } from "lucide-react";
import { risks } from "@/lib/demo-data";

export default function Page() {
  const critical = risks.filter((risk) => risk.severity === "CRITICAL").length;
  const high = risks.filter((risk) => risk.severity === "HIGH").length;
  const open = risks.filter((risk) => risk.status === "OPEN").length;
  return <section className="command-centre"><header className="command-header"><div className="command-title-group"><div className="command-kicker"><Radio size={14} /> Risk control</div><h1>Risk Register</h1><p>Portfolio threats, ownership and mitigation tracked in one operational view.</p></div><span className="demo-status"><i /> Live register</span></header>
    <div className="command-metrics"><article className="command-metric tone-magenta"><div className="metric-top"><span>Active risks</span><ShieldAlert size={18} /></div><strong>{risks.length}</strong><div className="metric-foot"><span>Across the portfolio</span><ArrowUpRight size={14} /></div></article><article className="command-metric tone-magenta"><div className="metric-top"><span>Critical</span><AlertTriangle size={18} /></div><strong>{critical}</strong><div className="metric-foot"><span>Immediate escalation</span></div></article><article className="command-metric tone-amber"><div className="metric-top"><span>High severity</span><AlertTriangle size={18} /></div><strong>{high}</strong><div className="metric-foot"><span>Director attention</span></div></article><article className="command-metric tone-amber"><div className="metric-top"><span>Open</span><ShieldAlert size={18} /></div><strong>{open}</strong><div className="metric-foot"><span>Mitigation active</span></div></article></div>
    <article className="command-panel"><div className="panel-heading"><div><span className="panel-label">Control register</span><h2>Portfolio risk exposure</h2></div><span className="panel-meta">{risks.length} tracked</span></div><div className="project-register" role="table" aria-label="Risks"><div className="project-row project-row-head" role="row"><span>Risk</span><span>Project / owner</span><span>Rating</span><span>Control status</span></div>{risks.map((risk) => <div className="project-row" role="row" key={risk.id}><div><strong>{risk.description}</strong><small>{risk.mitigation}</small></div><div><span>{risk.project}</span><small>Owner: {risk.owner}</small></div><div><span className={`rag-chip ${risk.severity === "CRITICAL" ? "rag-red" : risk.severity === "HIGH" ? "rag-amber" : "rag-green"}`}><i />{risk.severity}</span><small>{risk.likelihood} likelihood</small></div><div><strong className={risk.status === "OPEN" ? "text-risk" : "text-positive"}>{risk.status.replace("_", " ")}</strong><small>Control review active</small></div></div>)}</div></article>
  </section>;
}
