import { ArrowUpRight, CheckCircle2, CircleDashed, ClipboardCheck, Radio } from "lucide-react";
import { deliverables } from "@/lib/demo-data";

export default function Page() {
  const blocked = deliverables.filter((item) => item.status === "BLOCKED").length;
  const approved = deliverables.filter((item) => item.qa === "APPROVED").length;
  const progress = deliverables.filter((item) => item.status === "IN_PROGRESS").length;
  return <section className="command-centre"><header className="command-header"><div className="command-title-group"><div className="command-kicker"><Radio size={14} /> Delivery control</div><h1>Deliverables</h1><p>Design outputs, ownership, issue state and technical assurance.</p></div><span className="demo-status"><i /> Demo register</span></header>
    <div className="command-metrics"><article className="command-metric tone-cyan"><div className="metric-top"><span>Total outputs</span><ClipboardCheck size={18} /></div><strong>{deliverables.length}</strong><div className="metric-foot"><span>Portfolio-wide</span><ArrowUpRight size={14} /></div></article><article className="command-metric tone-cyan"><div className="metric-top"><span>In progress</span><CircleDashed size={18} /></div><strong>{progress}</strong><div className="metric-foot"><span>Active production</span></div></article><article className="command-metric tone-magenta"><div className="metric-top"><span>Blocked</span><CircleDashed size={18} /></div><strong>{blocked}</strong><div className="metric-foot"><span>Requires intervention</span></div></article><article className="command-metric tone-cyan"><div className="metric-top"><span>QA approved</span><CheckCircle2 size={18} /></div><strong>{approved}</strong><div className="metric-foot"><span>Ready or issued</span></div></article></div>
    <article className="command-panel"><div className="panel-heading"><div><span className="panel-label">Output register</span><h2>Controlled deliverables</h2></div><span className="panel-meta">{deliverables.length} records</span></div><div className="project-register" role="table" aria-label="Deliverables"><div className="project-row project-row-head" role="row"><span>Deliverable</span><span>Ownership</span><span>Status</span><span>Issue control</span></div>{deliverables.map((item) => <div className="project-row" role="row" key={item.id}><div><strong>{item.title}</strong><small>{item.project} · {item.discipline}</small></div><div><span>{item.owner}</span><small>Due {item.due}</small></div><div><span className={`rag-chip ${item.status === "BLOCKED" ? "rag-red" : item.status === "COMPLETE" ? "rag-green" : "rag-amber"}`}><i />{item.status.replace("_", " ")}</span><small>QA {item.qa.replaceAll("_", " ")}</small></div><div><strong>{item.revision}</strong><small>{item.issue}</small></div></div>)}</div></article>
  </section>;
}
