import { ArrowUpRight, BriefcaseBusiness, Radio, TrendingDown } from "lucide-react";
import { fees, money } from "@/lib/demo-data";

export default function Page() {
  const agreed = fees.reduce((sum, fee) => sum + fee.agreed, 0);
  const forecast = fees.reduce((sum, fee) => sum + fee.forecast, 0);
  const exposure = fees.filter((fee) => fee.variance < 0).reduce((sum, fee) => sum + Math.abs(fee.variance), 0);
  return <section className="command-centre"><header className="command-header"><div className="command-title-group"><div className="command-kicker"><Radio size={14} /> Commercial control</div><h1>Fees &amp; Commercial</h1><p>Agreed fee, delivery forecast and emerging portfolio exposure.</p></div><span className="demo-status"><i /> June forecast</span></header>
    <div className="command-metrics"><article className="command-metric tone-cyan"><div className="metric-top"><span>Agreed fees</span><BriefcaseBusiness size={18} /></div><strong>{money(agreed)}</strong><div className="metric-foot"><span>Current appointments</span><ArrowUpRight size={14} /></div></article><article className="command-metric tone-amber"><div className="metric-top"><span>Forecast cost</span><BriefcaseBusiness size={18} /></div><strong>{money(forecast)}</strong><div className="metric-foot"><span>Latest estimate</span></div></article><article className="command-metric tone-magenta"><div className="metric-top"><span>Gross exposure</span><TrendingDown size={18} /></div><strong>{money(exposure)}</strong><div className="metric-foot"><span>Overspend risk</span></div></article><article className="command-metric tone-magenta"><div className="metric-top"><span>At-risk projects</span><TrendingDown size={18} /></div><strong>{fees.filter((fee) => fee.variance < 0).length}</strong><div className="metric-foot"><span>Forecast above fee</span></div></article></div>
    <article className="command-panel"><div className="panel-heading"><div><span className="panel-label">Commercial register</span><h2>Project fee position</h2></div><span className="panel-meta">{fees.length} commissions</span></div><div className="project-register" role="table" aria-label="Fees"><div className="project-row project-row-head" role="row"><span>Project</span><span>Agreed fee</span><span>Forecast</span><span>Variance</span></div>{fees.map((fee) => <div className="project-row" role="row" key={fee.project}><div><strong>{fee.project}</strong><small>Current appointment</small></div><div><strong>{money(fee.agreed)}</strong><small>agreed</small></div><div><strong>{money(fee.forecast)}</strong><small>latest forecast</small></div><div><strong className={fee.variance < 0 ? "text-risk" : "text-positive"}>{money(fee.variance)}</strong><small>{fee.status}</small></div></div>)}</div></article>
  </section>;
}
