import { ArrowUpRight, Box, CheckCircle2, Radio } from "lucide-react";
import { bimRecords } from "@/lib/demo-data";

export default function Page() {
  const approved = bimRecords.filter((record) => record.status === "APPROVED").length;
  return <section className="command-centre"><header className="command-header"><div className="command-title-group"><div className="command-kicker"><Radio size={14} /> Digital governance</div><h1>BIM / Revit</h1><p>Model status, discipline ownership and coordination assurance.</p></div><span className="demo-status"><i /> Model register</span></header>
    <div className="command-metrics"><article className="command-metric tone-cyan"><div className="metric-top"><span>Controlled models</span><Box size={18} /></div><strong>{bimRecords.length}</strong><div className="metric-foot"><span>Current portfolio</span><ArrowUpRight size={14} /></div></article><article className="command-metric tone-cyan"><div className="metric-top"><span>Approved</span><CheckCircle2 size={18} /></div><strong>{approved}</strong><div className="metric-foot"><span>Coordination complete</span></div></article><article className="command-metric tone-amber"><div className="metric-top"><span>In coordination</span><Box size={18} /></div><strong>{bimRecords.length - approved}</strong><div className="metric-foot"><span>Review active</span></div></article><article className="command-metric tone-cyan"><div className="metric-top"><span>Disciplines</span><Box size={18} /></div><strong>{new Set(bimRecords.map((r) => r.discipline)).size}</strong><div className="metric-foot"><span>Federated coverage</span></div></article></div>
    <article className="command-panel"><div className="panel-heading"><div><span className="panel-label">Information management</span><h2>Model control register</h2></div><span className="panel-meta">Latest checks</span></div><div className="project-register" role="table" aria-label="BIM models"><div className="project-row project-row-head" role="row"><span>Model</span><span>Project</span><span>Status</span><span>Verification</span></div>{bimRecords.map((record) => <div className="project-row" role="row" key={record.id}><div><strong>{record.model}</strong><small>{record.discipline} authoring model</small></div><div><span>{record.project}</span><small>Controlled environment</small></div><div><span className={`rag-chip ${record.status === "APPROVED" ? "rag-green" : "rag-amber"}`}><i />{record.status}</span></div><div><strong>{record.checked}</strong><small>last checked</small></div></div>)}</div></article>
  </section>;
}
