import { ArrowUpRight, FileCheck2, FileText, Radio } from "lucide-react";
import { reports } from "@/lib/demo-data";

export default function Page() {
  const issued = reports.filter((report) => report.status === "ISSUED").length;
  return <section className="command-centre"><header className="command-header"><div className="command-title-group"><div className="command-kicker"><Radio size={14} /> Reporting control</div><h1>Client Reports</h1><p>Audience-controlled progress reporting and issue status.</p></div><span className="demo-status"><i /> June reporting</span></header>
    <div className="command-metrics"><article className="command-metric tone-cyan"><div className="metric-top"><span>Reports</span><FileText size={18} /></div><strong>{reports.length}</strong><div className="metric-foot"><span>Current cycle</span><ArrowUpRight size={14} /></div></article><article className="command-metric tone-cyan"><div className="metric-top"><span>Issued</span><FileCheck2 size={18} /></div><strong>{issued}</strong><div className="metric-foot"><span>Released to clients</span></div></article><article className="command-metric tone-amber"><div className="metric-top"><span>Draft</span><FileText size={18} /></div><strong>{reports.length - issued}</strong><div className="metric-foot"><span>Awaiting approval</span></div></article><article className="command-metric tone-cyan"><div className="metric-top"><span>Client audience</span><FileCheck2 size={18} /></div><strong>{reports.filter((r) => r.audience === "CLIENT").length}</strong><div className="metric-foot"><span>External reporting</span></div></article></div>
    <article className="command-panel"><div className="panel-heading"><div><span className="panel-label">Report register</span><h2>Controlled client outputs</h2></div><span className="panel-meta">{reports.length} records</span></div><div className="project-register" role="table" aria-label="Client reports"><div className="project-row project-row-head" role="row"><span>Report</span><span>Project</span><span>Status</span><span>Issue date</span></div>{reports.map((report) => <div className="project-row" role="row" key={report.id}><div><strong>{report.title}</strong><small>{report.audience} audience</small></div><div><span>{report.project}</span><small>Monthly reporting cycle</small></div><div><span className={`rag-chip ${report.status === "ISSUED" ? "rag-green" : "rag-amber"}`}><i />{report.status}</span></div><div><strong>{report.date}</strong><small>{report.status === "ISSUED" ? "issued" : "target issue"}</small></div></div>)}</div></article>
  </section>;
}
